try fix again

diff --git a/.github/workflows/deploy-env.yml b/.github/workflows/deploy-env.yml
--- a/.github/workflows/deploy-env.yml
+++ b/.github/workflows/deploy-env.yml
@@ -18,15 +18,6 @@ on:
       api_base_url:
         required: true
         type: string
-      role_arn:
-        required: true
-        type: string
-      db_user:
-        required: true
-        type: string
-    secrets:
-      db_password:
-        required: true
 
 permissions:
   contents: read
@@ -58,14 +49,18 @@ jobs:
           --health-retries 5
 
     steps:
-      - name: Validate inputs
+      - name: Validate env vars & secrets
         run: |
-          if [ -z "${{ inputs.role_arn }}" ]; then
-            echo "ROLE ARN is missing (inputs.role_arn)"; exit 1;
+          if [ -z "${{ vars.ROLE_ARN }}" ]; then
+            echo "ROLE ARN is missing (vars.ROLE_ARN)"; exit 1;
           fi
-          if [ -z "${{ inputs.db_user }}" ]; then
-            echo "DB_USER is missing (inputs.db_user)"; exit 1;
+          if [ -z "${{ vars.DB_USER }}" ]; then
+            echo "DB_USER is missing (vars.DB_USER)"; exit 1;
           fi
+          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
+            echo "DB_PASSWORD is missing (secrets.DB_PASSWORD)"; exit 1;
+          fi
+
       - name: Checkout source
         uses: actions/checkout@v4
         with:
@@ -94,7 +89,7 @@ jobs:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: ${{ inputs.role_arn }}
+          role-to-assume: ${{ vars.ROLE_ARN }}
           aws-region: ${{ env.AWS_REGION }}
 
       - name: Install AWS CDK CLI
@@ -106,9 +101,9 @@ jobs:
           cdk deploy $STACK_NAME-${{ inputs.stack_suffix }} \
             --require-approval never \
             -c stage=${{ inputs.stack_suffix }} \
-            --parameters DbUser=${{ inputs.db_user }} \
-            --parameters DbPassword=${{ secrets.db_password }}
-
+            --parameters DbUser=${{ vars.DB_USER }} \
+            --parameters DbPassword=${{ secrets.DB_PASSWORD }}
+      
       - name: Run DB migrations
         run: |
           MIGRATE_FN=$(aws cloudformation describe-stacks \
